<a href="https://colab.research.google.com/github/DipaliKhatua/Data-Science/blob/master/Deep_Learning_Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available, Using CPU")

GPU is available
Using GPU Tesla T4


Create a Tensor

In [4]:
a = torch.empty(2,3)
type(a)

torch.Tensor

In [5]:
print(a)

tensor([[2.6610e+23, 1.0547e-08, 2.1707e-18],
        [4.5447e+30, 7.0062e+22, 2.1715e-18]])


In [6]:
# Uisang Zeros
b = torch.zeros(2,3)
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# Using Ones
c = torch.ones(2,3)
print(c)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# random value
d = torch.rand(2,3)
print(d)

tensor([[0.9189, 0.7855, 0.7886],
        [0.5712, 0.4280, 0.2178]])


In [11]:
# Creating tensor using list
list_data = [[1,2,3], [4,5,6]]
e = torch.tensor(list_data)

In [12]:
print(e)
type(e)

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Tensor

In [13]:
e.shape

torch.Size([2, 3])