## Support Vector Regression Algorithm
- Business Problem - Bangalore House Price Prediction
- Using Support Vector Regression - Supervised Machine Learning Algorithm

In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

In [3]:
data = pd.read_csv("bangalore house price prediction OHE-data.csv")

In [4]:
data.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [5]:
X = data.drop('price', axis=1)
y = data['price']

In [6]:
print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


### Feature Scal;ing

In [11]:
standrd_scaler = StandardScaler()
standrd_scaler.fit(X_train)
X_train = standrd_scaler.transform(X_train)
X_test = standrd_scaler.transform(X_test)

## Support Vector Regression - ML Model Training

In [13]:
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(X_train, y_train)
svr_rbf.score(X_test, y_test)
 
svr_linear = SVR(kernel='linear')
svr_linear.fit(X_train, y_train)
svr_linear.score(X_test, y_test)
 
svr_poly = SVR(kernel='poly',degree=2,)
svr_poly.fit(X_train, y_train)
svr_poly.score(X_test, y_test)

0.07507719012985958

## Predict the value of Home and Test

In [14]:
X_test[0]

array([-0.44422611,  0.54630035, -0.34334897, -0.55044507, -0.72383255,
        0.57680968, -0.47233992, -0.25703648,  0.50597314, -0.18727461,
       -0.16162122, -0.15580825, -0.1288342 , -0.13023539, -0.12812824,
       -0.12234347,  7.59747652, -0.12741862, -0.12234347, -0.10909925,
       -0.1082724 , -0.1082724 , -0.11472827, -0.10743948, -0.09218776,
       -0.09315135, -0.08823182, -0.08923672, -0.09023078, -0.08195215,
       -0.08514823, -0.0830308 , -0.08514823, -0.07276497, -0.07975227,
       -0.07975227, -0.07749158, -0.0739743 , -0.06901264, -0.0751646 ,
       -0.07153563, -0.0751646 , -0.0751646 , -0.0751646 , -0.07749158,
       -0.07633675, -0.07276497, -0.06901264, -0.0739743 , -0.07276497,
       -0.07028523, -0.06504853, -0.0677166 , -0.0677166 , -0.0677166 ,
       -0.06504853, -0.07153563, -0.06367332, -0.06226825, -0.06639573,
       -0.06226825, -0.06367332, -0.06504853, -0.06504853, -0.06504853,
       -0.06083125, -0.05785186, -0.06639573, -0.06226825, -0.06

In [15]:
svr_linear.predict([X_test[0]])

array([43.19939184])

In [17]:
y_pred = svr_linear.predict(X_test)

In [18]:
y_pred

array([43.19939184, 60.99132775, 67.27973659, ..., 55.79001653,
       16.06977223, 47.0151836 ])

In [19]:
y_test

960      47.0
132      60.0
2431     65.0
2229    325.0
4503     60.0
        ...  
4970     48.0
553     205.0
1397     56.5
4056     26.0
1817     49.0
Name: price, Length: 1424, dtype: float64

In [22]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
 
print('MSE = ', mse)
print('RMSE = ', rmse)

MSE =  1923.325071295144
RMSE =  43.85573019908737
