### Python Numpy Array  Concatination and Split

In [2]:
import numpy as np

In [3]:
array_1 = np.arange(1,17).reshape(4,4)
print(array_1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
array_2 = np.arange(17,33).reshape(4,4)
print(array_2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [8]:
list_1 = [1,2,3,4,8]
list_2 = [9,10,11,15]

In [9]:
# list concatenation
list_1 + list_2

[1, 2, 3, 4, 8, 9, 10, 11, 15]

In [10]:
array_1 + array_2 # getting added not concatenated

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [11]:
# array concatenation
np.concatenate((array_1, array_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [13]:
# row wise concatenation
row_cocat_array = np.concatenate((array_1,array_2), axis = 1)
print(row_cocat_array)

[[ 1  2  3  4 17 18 19 20]
 [ 5  6  7  8 21 22 23 24]
 [ 9 10 11 12 25 26 27 28]
 [13 14 15 16 29 30 31 32]]


In [14]:
# stack function (vertically concat)
np.vstack((array_1,array_2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [15]:
np.hstack((array_1, array_2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [17]:
np.hstack((array_1, array_2, array_1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [18]:
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
# Split Function
np.split(array_1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [20]:
list1 =  np.split(array_1,2)

In [21]:
type(list1)

list

In [22]:
np.split(array_1, 2, axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [24]:
array_1D = np.array([4,1,7,9,5])

In [25]:
np.split(array_1D, [1, 3])

[array([4]), array([1, 7]), array([9, 5])]