### Random Sampling With Numpy

In [2]:
import numpy as np
import random

In [3]:
np.random.random(1)

array([0.69492703])

In [5]:
ran_value = np.random.random((3,3))
print(ran_value)

[[0.78423223 0.34566143 0.23053508]
 [0.05196408 0.02705627 0.78999602]
 [0.17509227 0.85219834 0.72395754]]


In [6]:
type(ran_value)

numpy.ndarray

In [8]:
np.random.randint(1,4, (4,4))

array([[3, 2, 3, 3],
       [2, 3, 1, 2],
       [2, 2, 3, 1],
       [2, 2, 2, 3]])

In [9]:
np.random.randint(1,5, (2,4,4))

array([[[3, 1, 1, 3],
        [2, 4, 3, 1],
        [2, 2, 3, 4],
        [2, 4, 1, 2]],

       [[4, 1, 2, 4],
        [4, 2, 2, 3],
        [2, 2, 2, 3],
        [3, 1, 4, 4]]])

In [10]:
np.random.seed(10)
np.random.randint(1,5, (2,4,4))

array([[[2, 2, 1, 4],
        [1, 2, 4, 1],
        [2, 2, 1, 2],
        [2, 3, 1, 2]],

       [[1, 3, 1, 3],
        [1, 4, 1, 1],
        [4, 4, 3, 1],
        [4, 3, 3, 2]]])

In [11]:
np.random.seed(10)
np.random.randint(1,5, (2,4,4))

array([[[2, 2, 1, 4],
        [1, 2, 4, 1],
        [2, 2, 1, 2],
        [2, 3, 1, 2]],

       [[1, 3, 1, 3],
        [1, 4, 1, 1],
        [4, 4, 3, 1],
        [4, 3, 3, 2]]])

In [12]:
np.random.rand(3)

array([0.72175532, 0.29187607, 0.91777412])

In [13]:
np.random.rand(3,3)

array([[0.71457578, 0.54254437, 0.14217005],
       [0.37334076, 0.67413362, 0.44183317],
       [0.43401399, 0.61776698, 0.51313824]])

In [14]:
np.random.randn(3,3)

array([[ 1.12369125,  1.67262221,  0.09914922],
       [ 1.39799638, -0.27124799,  0.61320418],
       [-0.26731719, -0.54930901,  0.1327083 ]])

In [15]:
x = [1,2,3,4]
np.random.choice(x)

2

In [16]:
x = [1,2,3,4]
np.random.choice(x)

1

In [17]:
for i in range(20):
    print(np.random.choice(x))


3
1
1
1
2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3


In [18]:
x

[1, 2, 3, 4]

In [19]:
np.random.permutation(x)

array([4, 1, 2, 3])

In [20]:
np.random.permutation(x)

array([2, 4, 1, 3])

In [23]:
x_1 = np.random.shuffle(x)
print(x_1)

None
