### Numpy Functions :

In [1]:
import numpy as np

#### arrange()

In [2]:
#np.arange(start , end, stop)
array_1d = np.arange(1,13)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_array = np.arange(2 , 13 , 2)
print(even_array)

[ 2  4  6  8 10 12]


#### linspace()

In [ ]:
# np.array( srat range, end range, how many values needed withing the given range)
np.linspace(1 , 5, 4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

#### rehape()

In [6]:
# to convert 1-D array to 2-D or multi- dimensional
# array_2d = array_1d.reshape(2,6)
# print(array_2d)

array_2d = array_1d.reshape(3,4)
print(array_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
array_3d = array_1d.reshape(2,3,2)
print(array_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
array_arange = np.arange(1,13).reshape(2,6)
print(array_arange)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


##### ravel()  --> converts multi-dimensional array to 1-D

In [10]:
array_arange.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### flatten()  --> converts multi-dimensional array to 1-D

In [11]:
array_arange.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### transpose --> converts row to colmns

In [12]:
array_arange.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])