In [1]:
import numpy as np

In [2]:
matrix_1s = np.array([[1,1,1], [1,1,1], [1,1,1]])
print(matrix_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [4]:
mx_1s.dtype

dtype('float64')

In [5]:
mx_1s = np.ones((3,4), dtype = 'int')
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [6]:
mx_1s = np.ones((3,4), dtype = int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
mx_1s.dtype

dtype('int32')

In [8]:
mx_0s = np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
mx_0s = np.zeros((4,6), dtype= str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [10]:
em_str = ''
print(bool(em_str))

False


In [11]:
em_mx = np.empty((3,3))
print(em_mx)

[[4.67296746e-307 1.69121096e-306 1.42418987e-306]
 [1.42413555e-306 1.78019082e-306 1.37959740e-306]
 [6.23057349e-307 1.42419530e-306 0.00000000e+000]]
